# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
